{
    'ALLUSERSPROFILE': 'C:\\ProgramData',
    'APPDATA': 'C:\\Users\\dell\\AppData\\Roaming',
    'APR_ICONV_PATH': 'D:\\software\\JavaTools\\SVN\\iconv',
    'CATALINA_BASE': 'D:\\software\\JavaTools\\apache\\apache-tomcat-8.0.38',
    'CATALINA_HOME': 'D:\\software\\JavaTools\\apache\\apache-tomcat-8.0.38',
    'CLASSPATH': '.;D:\\software\\JavaTools\\JDK8_u101\\lib\\tools.jar;D:\\software\\JavaTools\\JDK8_u101\\lib\\dt.jar;D:\\software\\JavaTools\\apache\\apache-tomcat-8.0.38\\lib\\jsp-api.jar;D:\\software\\JavaTools\\apache\\apache-tomcat-8.0.38\\lib\\servlet-api.jar;D:\\DB_Drivers\\mysql-connector-java-5.1.30-bin.jar;E:\\2-xk-workspace\\MPXJ\\poi-3.15',
    'COLORTERM': 'truecolor',
    'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
    'COMPUTERNAME': 'XK-PC',
    'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',
    'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
    'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
    'EXEPATH': 'D:\\software\\Git\\bin',
    'FP_NO_HOST_CHECK': 'NO',
    'HOME': 'C:\\Users\\dell',
    'HOMEDRIVE': 'C:',
    'HOMEPATH': '\\Users\\dell',
    'JAVA_HOME': 'D:\\software\\JavaTools\\JDK8_u101',
    'LANG': 'zh_CN.UTF-8',
    'LOCALAPPDATA': 'C:\\Users\\dell\\AppData\\Local',
    'LOGONSERVER': '\\\\XK-PC',
    'M2_HOME': 'D:\\software\\JavaTools\\apache\\apache-maven-3.3.9',
    'M2_REPO': 'D:\\m2\\repository',
    'MSYSTEM': 'MINGW64',
    'NUMBER_OF_PROCESSORS': '4',
    'OLDPWD': 'E:/project/JSite',
    'OS': 'Windows_NT',
    'ONEDRIVE': 'C:\\Users\\dell\\OneDrive',
    'ONEDRIVECONSUMER': 'C:\\Users\\dell\\OneDrive',
    'PATH': 'D:\\software\\Git\\mingw64\\bin;D:\\software\\Git\\usr\\bin;C:\\Users\\dell\\bin;C:\\Ruby25-x64\\bin;C:\\Program Files (x86)\\NetSarang\\Xftp 6\\;C:\\Program Files (x86)\\NetSarang\\Xshell 6\\;D:\\software\\JavaTools\\JDK8_u101\\bin;D:\\software\\JavaTools\\apache\\apache-tomcat-8.0.38\\lib;D:\\software\\JavaTools\\apache\\apache-tomcat-8.0.38\\bin;D:\\software\\JavaTools\\apache\\apache-maven-3.3.9\\bin;D:\\software\\JavaTools\\apache\\apache-maven-3.3.9\\bin;D:\\m2\\repository;D:\\software\\JavaTools\\SVN\\bin;D:\\software\\MySQL_5_7\\MySQL\\bin;D:\\software\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Tesseract-OCR;C:\\Users\\dell\\AppData\\Local\\GitHubDesktop\\bin;D:\\software\\MySQL_5_7\\MySQL\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\SysWOW64;C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Scripts;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\Users\\dell\\AppData\\Roaming\\npm;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\Tesseract-OCR;C:\\Users\\dell\\AppData\\Local\\Programs\\Microsoft VS Code\\bin',
    'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
    'PLINK_PROTOCOL': 'ssh',
    'PROCESSOR_ARCHITECTURE': 'AMD64',
    'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
    'PROCESSOR_LEVEL': '6',
    'PROCESSOR_REVISION': '3c03',
    'PROGRAMFILES': 'C:\\Program Files',
    'PS1': '\\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
    'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
    'PUBLIC': 'C:\\Users\\Public',
    'PWD': 'E:/project/JSite/back_end',
    'PROGRAMDATA': 'C:\\ProgramData',
    'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
    'PROGRAMW6432': 'C:\\Program Files',
    'SESSIONNAME': 'Console',
    'SHLVL': '1',
    'SYSTEMDRIVE': 'C:',
    'SYSTEMROOT': 'C:\\Windows',
    'TEMP': 'C:\\Users\\dell\\AppData\\Local\\Temp',
    'TERM': 'cygwin',
    'TERM_PROGRAM': 'vscode',
    'TERM_PROGRAM_VERSION': '1.38.0',
    'TESSDATA_PREFIX': 'C:\\Program Files (x86)\\Tesseract-OCR\\',
    'TMP': 'C:\\Users\\dell\\AppData\\Local\\Temp',
    'USERDOMAIN': 'XK-PC',
    'USERNAME': 'dell',
    'USERPROFILE': 'C:\\Users\\dell',
    'VS110COMNTOOLS': 'D:\\software\\MyTools\\VS2012U\\Common7\\Tools\\',
    'WINDIR': 'C:\\Windows',
    '_': 'C:/ProgramData/Anaconda3/python',
    'WINDOWS_TRACING_FLAGS': '3',
    'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log',
    'DJANGO_SETTINGS_MODULE': 'BlogBackEnd.settings',
    'RUN_MAIN': 'true',
    'SERVER_NAME': 'xk-PC',
    'GATEWAY_INTERFACE': 'CGI/1.1',
    'SERVER_PORT': '8000',
    'REMOTE_HOST': '',
    'CONTENT_LENGTH': '',
    'SCRIPT_NAME': '',
    'SERVER_PROTOCOL': 'HTTP/1.1',
    'SERVER_SOFTWARE': 'WSGIServer/0.2',
    'REQUEST_METHOD': 'GET',
    'PATH_INFO': '/list/tags',
    'QUERY_STRING': '',
    'REMOTE_ADDR': '127.0.0.1',
    'CONTENT_TYPE': 'text/plain',
    'HTTP_X_FORWARDED_HOST': 'localhost:3000',
    'HTTP_X_FORWARDED_PROTO': 'http',
    'HTTP_X_FORWARDED_PORT': '3000',
    'HTTP_X_FORWARDED_FOR': '127.0.0.1',
    'HTTP_COOKIE': 'csrftoken=82iaFMlaC4JFPH5ZZQCnfxt9LvCLRYJrP1gAR8kliO2Xl1vJ1YBj0fivIgSutsas; sessionid=crzja32k5grpf8zmq99h9nxcxe39mc3f',
    'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.9',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
    'HTTP_REFERER': 'http://localhost:3000/',
    'HTTP_SEC_FETCH_SITE': 'same-origin',
    'HTTP_SEC_FETCH_MODE': 'cors',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36',
    'HTTP_ACCEPT': 'application/json, text/plain, */*',
    'HTTP_CONNECTION': 'close',
    'HTTP_HOST': 'localhost:8000',
    'wsgi.input': '<django.core.handlers.wsgi.LimitedStream object at 0x000000000490A828 >',
    'wsgi.errors': "<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>",
    'wsgi.version': '(1, 0)',
    'wsgi.run_once': False,
    'wsgi.url_scheme': 'http',
    'wsgi.multithread': True,
    'wsgi.multiprocess': False,
    'wsgi.file_wrapper': "<class 'wsgiref.util.FileWrapper'>",
    'CSRF_COOKIE': '82iaFMlaC4JFPH5ZZQCnfxt9LvCLRYJrP1gAR8kliO2Xl1vJ1YBj0fivIgSutsas'
}