# Generated by Django 2.2.2 on 2019-09-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='gold', max_length=7),
        ),
    ]
