# Generated by Django 2.2.2 on 2019-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbModel', '0002_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='未命名', max_length=1000),
        ),
    ]
